# Generated by Django 3.0.8 on 2020-08-01 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=1234567890, max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(5, 'Alumni'), (10, 'AlumniStaff'), (15, 'Staff'), (20, 'College'), (25, 'CollegeAdmin'), (30, 'Directorate'), (0, 'Normal')], default=0),
        ),
    ]
