name: alumni
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  form_field_validator: any
  http: ^0.12.1
  file_picker: ^1.12.0
  path: ^1.6.0
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.7+3
  flutter_icons: ^1.1.0
  dropdown_formfield: ^0.1.2
  searchable_dropdown: ^1.1.3
  flutter_webview_plugin: any
  page_transition: "^1.1.5"
  rflutter_alert: ^1.0.3
  image_picker: ^0.6.7+2
  custom_switch: ^0.0.1
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.1
  flutter_secure_storage: ^3.3.3
  jwt_decoder: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
      - family: OpenSans     
        fonts:
          - asset: assets/fonts/OpenSans-Bold.ttf
  assets:
    - assets/images/
  uses-material-design: true

  